# Generated by Django 3.0.1 on 2019-12-30 16:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayinfo',
            name='info',
        ),
        migrations.AddField(
            model_name='dayinfo',
            name='mood',
            field=models.CharField(choices=[('N', 'NEUTRAL'), ('D', 'DEPRESSIVE'), ('H', 'HAPPY')], default='N', max_length=20),
        ),
        migrations.AddField(
            model_name='dayinfo',
            name='note',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dayinfo',
            name='thoughts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), null=True, size=None),
        ),
    ]
