# Generated by Django 3.0.1 on 2019-12-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0002_auto_20191230_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayinfo',
            name='thoughts',
        ),
    ]
