# Generated by Django 3.0.1 on 2020-01-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0003_remove_dayinfo_thoughts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
