# Generated by Django 3.0.1 on 2020-01-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayinfo',
            name='tasks',
            field=models.ManyToManyField(to='mycalendar.Task'),
        ),
    ]
