# Generated by Django 3.0.1 on 2020-01-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0005_dayinfo_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayinfo',
            name='day',
        ),
        migrations.RemoveField(
            model_name='dayinfo',
            name='month',
        ),
        migrations.RemoveField(
            model_name='dayinfo',
            name='year',
        ),
        migrations.AddField(
            model_name='dayinfo',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
