# Generated by Django 3.0.1 on 2020-01-20 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0007_auto_20200118_2203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DayInfo',
            new_name='Day',
        ),
    ]
