# Generated by Django 3.0.1 on 2020-01-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0008_auto_20200120_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finish_date',
            field=models.DateField(auto_now=True),
        ),
    ]
