# Generated by Django 3.0.1 on 2020-01-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0010_auto_20200121_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finish_date',
            field=models.DateField(null=True),
        ),
    ]
