# Generated by Django 3.0.1 on 2020-06-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0011_auto_20200121_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
