# Generated by Django 3.0.1 on 2020-06-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0012_auto_20200617_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='note',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
