# Generated by Django 3.0.1 on 2019-12-27 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='No text', max_length=500)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
