# Generated by Django 3.0.1 on 2019-12-28 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='category',
            field=models.CharField(choices=[('DS', 'DISCOVERIES'), ('DP', 'DEPRESSIVE'), ('HP', 'HAPPY'), ('O', 'OTHER')], default='O', max_length=2),
        ),
        migrations.AddField(
            model_name='log',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='log',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
