# Generated by Django 3.0.1 on 2019-12-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20191228_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
