# Generated by Django 3.0.1 on 2019-12-28 18:11

from django.db import migrations
from datetime import timezone


def fill_date_time(apps, schema_editor):
	Log = apps.get_model("log", "Log")
	date = timezone.now().date()
	time = timezone.now().time()
	for log in Log.objects.all():
		log.date = date
		log.time = time
		log.save()

class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20191229_0003'),
    ]

    operations = [
    	migrations.RunPython(fill_date_time),
    ]
