# Generated by Django 3.0.1 on 2019-12-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_auto_20191229_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.TimeField(),
        ),
    ]
