# Generated by Django 3.0.1 on 2019-12-28 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_auto_20191229_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
