# Generated by Django 3.0.1 on 2020-01-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='value_type',
            field=models.CharField(choices=[('G', 'GOOD'), ('B', 'BAD')], default='G', max_length=20),
        ),
    ]
