# Generated by Django 3.0.1 on 2020-01-03 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='happyness',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
