# Generated by Django 3.0.1 on 2020-01-14 12:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20200103_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='happyness',
            new_name='happiness',
        ),
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='person',
            name='logo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='strength_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=50), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='person',
            name='weakness_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=50), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='strengths',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='weaknesses',
            field=models.CharField(default='', max_length=50),
        ),
    ]
