# Generated by Django 3.0.1 on 2020-01-14 12:07

from django.db import migrations


def fill_list(apps, schema_editor):
    Person = apps.get_model('people', 'Person')
    for cur in Person.objects.all():
        l = cur.strength_list
        l.append(cur.strengths)
        cur.strength_list = l
        l = cur.weakness_list
        l.append(cur.weaknesses)
        cur.weakness_list = l
        cur.save()

class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20200114_1800'),
    ]

    operations = [
        migrations.RunPython(fill_list),
    ]
