# Generated by Django 3.0.1 on 2020-01-14 12:13

from django.db import migrations


def fill_logo(apps, schema_editor):
    Person = apps.get_model('people', 'Person')
    for cur in Person.objects.all():
        cur.logo = cur.img
        cur.save()

class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20200114_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='person',
            name='weaknesses',
        ),
        migrations.RunPython(fill_logo)
    ]
