# Generated by Django 3.0.1 on 2020-01-16 15:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20200114_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='habit_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=50), blank=True, default=[], size=None),
        ),
    ]
