# Generated by Django 3.0.1 on 2020-01-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20200116_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='field',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='occupation',
            field=models.CharField(default='', max_length=100),
        ),
    ]
