# Generated by Django 3.0.7 on 2020-08-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='commentary',
        ),
        migrations.RemoveField(
            model_name='person',
            name='field',
        ),
        migrations.RemoveField(
            model_name='person',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='person',
            name='occupation',
        ),
    ]
