# Generated by Django 3.0.1 on 2020-01-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='commentary',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='field',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
