# Generated by Django 3.0.7 on 2020-08-13 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_entry_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='user',
        ),
    ]
