# Generated by Django 3.0.7 on 2020-08-14 11:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_remove_entry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='entries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=50), blank=True, default=list, size=None),
        ),
    ]
