# Generated by Django 3.0.1 on 2020-06-14 05:54

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dtree', '0003_econtree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree', models.CharField(max_length=100)),
                ('node', models.CharField(max_length=100)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dtree.Tree')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='econtree',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='ruletree',
            name='parent',
        ),
        migrations.DeleteModel(
            name='CodeforcesTree',
        ),
        migrations.DeleteModel(
            name='EconTree',
        ),
        migrations.DeleteModel(
            name='RuleTree',
        ),
    ]
